services:
  - type: web
    name: bubblemeet
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -b 0.0.0.0:$PORT
    envVars:
      - key: FIREBASE_CREDS_JSON
        sync: false
